server:
  port: 8082

spring:
  application:
    name: transit-tracker-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: transit-tracker-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        enable.auto.commit: true
        auto.commit.interval.ms: 1000


# Kafka Topic Configuration
kafka:
  topics:
    vehicle-positions: vehicle-positions

# WebSocket Configuration
websocket:
  endpoint: /ws
  allowed-origins: "*"

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    com.bustracker.tracker: INFO
    org.springframework.kafka: WARN
    org.apache.kafka: WARN
    org.springframework.web.socket: INFO
    root: INFO
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"