# Local development environment with containerized Kafka
# Usage: docker-compose -f docker-compose.yml -f docker-compose.local.yml up

services:
  data-ingestion-service:
    environment:
      SPRING_PROFILES_ACTIVE: "local"
      # Kafka settings for local containerized Kafka
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_API_KEY: ""  # Not needed for local Kafka
      KAFKA_API_SECRET: ""  # Not needed for local Kafka
      # TransLink API (from .env file)
      TRANSLINK_API_KEY: "${TRANSLINK_API_KEY}"
      # Development settings
      POLLING_ENABLED: "true"
      POLLING_INTERVAL_SECONDS: "10"  # Faster polling for development
      JAVA_OPTS: "-Xmx512m -Xms256m -server -XX:+UseG1GC"
    depends_on:
      kafka:
        condition: service_healthy

  transit-tracker-service:
    environment:
      SPRING_PROFILES_ACTIVE: "local"
      # Kafka settings for local containerized Kafka
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_API_KEY: ""  # Not needed for local Kafka
      KAFKA_API_SECRET: ""  # Not needed for local Kafka
      # Development settings
      JAVA_OPTS: "-Xmx1g -Xms512m -server -XX:+UseG1GC"
      # Email Config for Feedback
      SMTP_HOST: "${SMTP_HOST}"
      SMTP_PORT: "${SMTP_PORT}"
      SMTP_USERNAME: "${SMTP_USERNAME}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      FEEDBACK_EMAIL_TO: "${FEEDBACK_EMAIL_TO}"
      FEEDBACK_EMAIL_FROM: "${FEEDBACK_EMAIL_FROM}"
    depends_on:
      kafka:
        condition: service_healthy