services:
  # Data Ingestion Service
  data-ingestion-service:
    build:
      context: ..
      dockerfile: data-ingestion-service/Dockerfile
    container_name: transit-data-ingestion
    ports:
      - "8081:8081"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "${KAFKA_BOOTSTRAP_SERVERS}"
      KAFKA_API_KEY: "${KAFKA_API_KEY}"
      KAFKA_API_SECRET: "${KAFKA_API_SECRET}"
      TRANSLINK_API_KEY: "${TRANSLINK_API_KEY}"
      POLLING_ENABLED: "${POLLING_ENABLED:-true}"
      POLLING_INTERVAL_SECONDS: "${POLLING_INTERVAL_SECONDS:-30}"
      JAVA_OPTS: "${DATA_INGESTION_JAVA_OPTS:--Xmx2g -Xms1g -server}"
      SPRING_PROFILES_ACTIVE: "prod"
    networks:
      - transit-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  # Transit Tracker Service
  transit-tracker-service:
    build:
      context: ..
      dockerfile: transit-tracker-service/Dockerfile
    container_name: transit-tracker
    ports:
      - "8082:8082"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "${KAFKA_BOOTSTRAP_SERVERS}"
      KAFKA_API_KEY: "${KAFKA_API_KEY}"
      KAFKA_API_SECRET: "${KAFKA_API_SECRET}"
      JAVA_OPTS: "${TRANSIT_TRACKER_JAVA_OPTS:--Xmx4g -Xms2g -server}"
      SPRING_PROFILES_ACTIVE: "prod"
    volumes:
      - ../google_transit.zip:/app/data/google_transit.zip:ro
      - transit-logs:/app/logs
    networks:
      - transit-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  # Nginx reverse proxy (optional, for SSL termination and load balancing)
  nginx:
    image: nginx:alpine
    container_name: transit-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - data-ingestion-service
      - transit-tracker-service
    networks:
      - transit-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

volumes:
  transit-logs:
    driver: local

networks:
  transit-network:
    driver: bridge
    name: transit-network